feat: add flip drop-down (video flags)
EvanHahn/ffmpeg-buddy pull request #5
Opened 2022-06-03 07:55 UTC by hagemt

Handles #4

2022-06-03 07:56 UTC, hagemt commented
![image](https://user-images.githubusercontent.com/593274/171812981-c7e1a74f-b42b-4dcb-b426-dc20f7fbaa92.png)

2022-06-03 11:23 UTC, EvanHahn requested changes
Looks great other than some extraneous changes. Thanks for doing this!

2022-06-03 11:23 UTC, EvanHahn commented on .eslintrc.json
> +  "root": true,
Could you revert this? I don't think they're really related to this PR.

I'd love to have them in a follow-up change, though!

2022-06-03 11:23 UTC, EvanHahn commented on package.json
> +    "dev": "serve src",
Similar to the above: could you revert the changes to this file?

2022-06-07 23:13 UTC, hagemt commented
I kept just the changes in `src` as requested, even though I'd politely suggest you also take the JSON changes while we're here, since it's the bare minimum to dev without a few minor annoyances. Knowing me, I'm probably not going to check back on this in all honesty. 🙂 Recently, ESLint wants root: true, to avoid the provenance of config in home directories.

P.S. Thanks for `helmet` and your other modules NPM. I didn't realize you're also the author of that, and on human note: I appreciate you as a maintainer. Cheers 🎉

2022-06-08 02:24 UTC, EvanHahn approved these changes
Thanks for doing this!

2022-06-08 02:25 UTC, merged

2022-06-08 02:27 UTC, EvanHahn commented
I re-added your `.eslintrc` changes in 3f0b5be254fb13b6c0963002d271fd4f660e63aa and 6d16fae67dfda7d8c762956e4142e56d40253f73.

Thanks again! I'll deploy this soon.